### ISSUE TITLE
SP2013 in 2010 mode support

### ISSUE THREAD

**Issue by chapstickbomber** [bravocg/core#1]
For 2013 environments in 2010 mode, the 2013 /_api  is exposed but doesn't load the same base javascript, so the SP.SOD.loadMultiple function does not exist, breaking BRAVO.Core on basically the last line, which is a shame since it seemed to work as expected otherwise when I chained the script loads as a workaround.

It might make sense to write a fallback for ensuring the last two SP scripts when loadMultiple is not defined.

**Comment by gunjandatta** [comment]
I haven't tested this library against 2013 running in 2010 mode. Does the SP.SOD.executeFunc method exist? I can update it to use that instead. Thanks for reporting this...

**Comment by gunjandatta** [comment]
This is what I would replace it with, if the executeFunc is available when running in 2010 mode.

// Ensure the dialog class is loaded
SP.SOD.executeFunc("sp.ui.dialog.js", "SP.UI.ModalDialog", function () {
    // Notify scripts that this class is loaded
    SP.SOD.notifyScriptLoadedAndExecuteWaitingJobs("bravo.modaldialog.js");
});

**Comment by chapstickbomber** [comment]
SP.SOD.executeFunc is available in my console in this 2013-in-2010-mode site, so that should work.

**Comment by gunjandatta** [comment]
Great. I'm working on adding the social api to the core library. I'll include this bug fix in the next update. Thank you for the help on this.

**Comment by gunjandatta** [comment]
I updated the latest code w/ this fix and added new apis as well.
