### ISSUE TITLE
dependencies on SP.js and client context

### ISSUE THREAD

**Issue by chapstickbomber** [bravocg/core#3]
As an exercise, I'm trying to build up an app with BRAVO from an empty ASPX.

This runs into issues with dependencies or core SP javascript and _spPageContextInfo, which really do not exist without a masterpage backing things.

BRAVO only needs SP and the context info a little bit. I'm playing with the code myself, but what do you think is the minimum substitute here?

**Comment by chapstickbomber** [comment]
http://sharepoint.stackexchange.com/questions/116359/bare-minimum-page-to-get-sppagecontextinfo-loaded

Found the most relevant info about it above.

Besides loading the SP javascript dependencies, the main key is to have the SharePoint:FormDigest tag inside your form tag. That alone populates it from the server, seems like.

**Comment by gunjandatta** [comment]
Nice find. I'll update the line of code:
`// Notify scripts that this class is loaded`
`SP.SOD.notifyScriptLoadedAndExecuteWaitingJobs("bravo.js");`

to

`// Ensure the dialog class is loaded`
`SP.SOD.executeFunc("sp.js", "SP.ClientContext", function () {`
`// Notify scripts that this class is loaded`
`SP.SOD.notifyScriptLoadedAndExecuteWaitingJobs("bravo.js");`
`});`

You'll have to use the following afterwards:
`SP.SOD.executeOrDelayUntilScriptLoaded(function() {`
`// Code goes here...`
`}, "bravo.js");`

**Comment by gunjandatta** [comment]
I updated the core code. Let me know if it works w/out the need of adding the FormDigest to the page.

**Comment by chapstickbomber** [comment]
Soooo....

```
      SP: "/_layouts/sp",

      SPruntime: "/_layouts/sp.runtime",

      SPcore: "/_layouts/sp.core",

      MSAjax: "/_layouts/MicrosoftAjax",

      MScore: "/_layouts/1033/core",

      MSinit: "/_layouts/1033/init"
```

I pull all this in with Require and a shim for the dependencies. In order to even call SP.SOD, at least some of these scripts must run. I'm not sure exactly what the dependency chain look like for the core SP scripts.

With all of them loading and the FormDigest in the page, BRAVO and SP scripts work fine in an otherwise empty ASPX page.

I haven't tested your changes to check if FormDigest is strictly necessary, but obviously SP.SOD can't bootstrap itself, so at some point, an empty ASPX page has to manage those dependencies directly.

If you want, I can contribute my requirejs/APSX approach as a wrapper for using BRAVO without a masterpage. In the big picture, a self-bootstrapping version of BRAVO is definitely possible, though probably not necessary for 90% of development cases. Just having a template is probably more than enough for the other 10%.

**Comment by gunjandatta** [comment]
I misread the issue, and thought you were referring to an empty web part page. I've had to load a script manually, for MDS work-arounds, so let me see if I can incorporate a check to load the default script and ensure the core scripts are loaded. This may end of being a decent fix for MDS enabled sites. If not, I'll take you up on the wrapper approach. If it's similar to what I said, then please provide the approach and I'll incorporate it in the library.

Thoughts?

**Comment by chapstickbomber** [comment]
I'll send you my wrapper config in the next few days. There still might be something broken in it that I've missed so far, so I'll ferment a bit in dev before the pull request.

I agree that making BRAVO robust for MDS does have a nice synergy with use in application/standalone pages.

**Comment by gunjandatta** [comment]
http://blog.repsaj.nl/index.php/2014/06/sp2013-provider-hosted-app-loading-scripts-in-order-and-waiting/

Steps to recreate error:
1) Access site using SP Designer
2) Create an ASPX page and store it in the Site Assets or Style Library
3) Add a script link to the core library
4) Error - Unable to create/use the core library

I've tried to load the script files manually, but you are absolutely right the <SharePoint:FormDigest runat="server" /> needs to be on the page for it to work. Just loading the files will not work. The link above is what I'm using for the order of loading the files, since I was running into errors based on certain classes not being available.

I wrote a "loadDependencies" method that is called by the other classes, to ensure the same error doesn't stop the JSLink or ModalDialog classes from loading. Additionally, I'd like a simple solution that would allow us to use a generic method to ensure the core dependencies are loaded.

Please take a look at this method and let me know what you think.

**Comment by gunjandatta** [comment]
Take a look at the latest, and let me know what you think. Below is the sample ASPX page I'm using to test.

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ Page Language="C#" %>
<%@ Register tagprefix="SharePoint" namespace="Microsoft.SharePoint.WebControls" assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml">

<head runat="server">
    <meta name="WebPartPageExpansion" content="full" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=10" />
    <title>Dev Page</title>
    <SharePoint:CssRegistration Name="default" runat="server"/>
    <SharePoint:ScriptLink runat="server" Localizable="False" Name="~sitecollection/style library/bravo/js/bravo.min.js"/>
    <script type="text/javascript">
    BRAVO.Core.loadDependencies(function() {
        var web = new BRAVO.Core.Web();
        if(web.exists) {
            document.body.innerHTML += "<h3>Web Title: " + web.Title + "</h3>";
        }
        else { console.error("Unable to load core web"); }
    });
    </script>
</head>

<body><form id="form1" runat="server">
    <SharePoint:FormDigest ID="FormDigest1" runat="server"></SharePoint:FormDigest>
</form></body>

</html>

```

**Comment by chapstickbomber** [comment]
This is pretty clean. I like it. 

I do think the FormDigest control is ultimately necessary, though I suppose it is possible to make manual REST calls and go grab and build out _spPageContextInfo piece by piece if it doesn't already exist, but that would probably not be very performant.

You could also add loadDependencies into the front of WebAsync and ListAsync, which would be a nice touch and makes the library feel even more _automagical_. Most devs working in blank ASPX pages wouldn't even need to use loadDependencies directly.

I'm going to continue with RequireJS since I have ~50 files to load on demand for views and models, anyway. I might refactor the BRAVO dependencies around this though, if it looks cleaner on the page.

**Comment by chapstickbomber** [comment]
But you are right about finding a better generic way to load the dependencies.

It might make sense to use a small black box solution for script loading, like [lazyload](https://github.com/rgrove/lazyload/) minified and stuffed into your loadDependencies function. Then you just have to add a note in your readme including the copyright info for it with a nice little thank you.

**Comment by gunjandatta** [comment]
You're absolutely right, the FormDigest is required to be there and thank you for the initial link it helped w/ the research. If there is a way to load it via JS, that would be ideal, but don't know if it's possible at the moment.

Each class (Core, JSLink & ModalDialog) all call the "load dependencies" method, which allows for multiple executions and ensures the code to add scripts is executed once. Adding it in front of the Async methods shouldn't be needed right? By the time the window loads, the scripts will have been loaded. Is this correct, or is my logic off here?

**Comment by chapstickbomber** [comment]
What I meant is that it is easy to put one asynchronous behavior in front of another and just chain the callbacks.

So if someone loaded an empty page with BRAVO in it, then directly called ListAsync, you could check the dependencies and load them if needed before calling the actual List method. Couldn't do this with the synchronous call, of course, since loadDependencies would have to come and complete explicitly beforehand. No reasonable way to do async in a sync wrapper until ES7 comes out, I believe.
